name: dico1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.1  
  http: ^1.2.0     
  intl: ^0.19.0     

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: Staatliches
      fonts:
        - asset: fonts/Staatliches-Regular.ttf
    - family: Oxygen
      fonts:
        - asset: fonts/Oxygen-Regular.ttf

        
